services:
  wordpress:
    source:
      type: docker
      image: wordpress
      copy:
        - ./plugins:/var/www/html/wp-contents/plugins
        - ./themes:/var/www/html/wp-contents/themes
        - ./scripts:/var/www/html/scripts/first-run.sh
      # first_run: ./scripts/first-run.sh
      boot: apache2
      final_image: .......................
    environment:
      APPLICATION_TYPE: PHP
      DEVELOPMENT_MODE: development
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "${my_db_name}"
      WORDPRESS_DB_USER: "${my_sql_user}"
      WORDPRESS_DB_PASSWORD: "${my_database_pass}"
    mount:
      - uploads:/var/www/html/wp-contents/uploads
      - cache:/var/cache/convesio
    route:
      - 8999:6500/https
      - 22:2222/ssh
      - 00:80/default
    lb_config: true
    scale:
      minimum: 1
      maximum: 2
      triggers:
        - observe: cpu
          is_above: 70
          metric_type: avarage
          action: up
          cooldown: 300
        - observe: cpu
          is_below: 50
          metric_type: avarage
          action: down
          cooldown: 300
 mysql:
    source:
      type: docker
      image: mysql:latest
      container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${root_password}
      MYSQL_DATABASE: ${my_db_name}
      MYSQL_USER: ${my_sql_user}
      MYSQL_PASSWORD: ${my_database_pass}
    route:
      - 3308:3306/http
      - 00:3306/default
    lb_config: false
    volumes:
      - /opt/components/controller/mysql:/var/lib/mysql
    resources:
      - CPU:100
      - MemoryMB:512

  phpmyadmin:
    source:
      type: docker
      image: phpmyadmin/phpmyadmin:latest
      container_name: my_phpmyadmin
    lb_config: true
    route:
      - "8088:80/http"
      - 00:80/default
    environment:
      PMA_HOST: mysql

storage:
  uploads:
    type: shared
    size: 100
    sftp: true
  cache:
    type: io
    size: 10

ui:
  inputs:
      - name: my_database_pass
        label: PASSWORD FOR WORDPRESS
        type: text
        required: true
        default: PASSWORD
        description: abcd
        size: 1x
      - name: my_db_name
        label: NAME FOR MYSQL DATABASE
        type: text
        required: true
        default: WORDPRESS
        description: NAME FOR MYSQL DATABASE
        size: 1x
      - name: my_sql_user
        label: NAME FOR MYSQL USER
        type: text
        required: true
        default: SUMAN
        description: PASSWORD FOR MYSQL USER
        size: 1x
